### ISSUE TITLE
Обычно компоненты jsx пишут в формате PascalCase

### ISSUE THREAD

**Issue by forwardomg** [klyukvushka/spaceX#1]
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-pascal-case.md

**Comment by klyukvushka** [comment]
@forwardomg наименование касается именно компонентов, а не файлов в которых они содержатся. но раз нет пока что структурных изменений в проекте, то для большей наглядности и файлы будут называться по такому же принципу как и сами компоненты

**Comment by klyukvushka** [comment]
#3 изменения названий компонентов + правки по коду
